version: "3"
services:
    nodedev:
        image: tfnodedev:latest
        restart: always
        volumes:
            - "/Users/zhaoguanxin/CODE/OTHER/traefik/nodedev:/app"
        labels:
            - "traefik.http.routers.nodedev.rule=Host(`nodedev.docker`)"
           
networks:
    default:
        external:
            name: traefik
