version: "3"

services:
    reverse-proxy:
        image: traefik:v2.2
        command: --api.insecure=true --providers.docker
        networks:
            - webgateway
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /Users/zhaoguanxin/CODE/traefik/traefik/traefik.toml:/etc/traefik.toml
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    webgateway:
        driver: bridge
