version: '3'
services:
  traefik:
    image: traefik:v2.2
    # 启用webUI 并告诉Traefile去监听docker的容器实例
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # 指定docker的sock文件来让traefik获取docker的事件，从而实现动态负载均衡
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/zhaoguanxin/CODE/OTHER/traefik/traefik/traefik.toml:/etc/traefik.toml # 挂载本地配置文件