version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    restart: always
    command: --configFile /etc/traefik.toml
    ports:
      - "80:80"
      - "8080:8080"
    networks: 
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik.toml:ro
      - ./config/:/etc/traefik/config/:ro

networks:
  traefik:
    external: true