[frontends]
  [frontends.frontend1]
  backend = "backend2"
    [frontends.frontend1.routes.test_1]
    rule = "Host:node-node"
  [frontends.frontend2]
  backend = "backend1"
    [frontends.frontend2.routes.test_1]
    rule = "Host:node-node;Path:/a"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = 'http://172.19.0.6:3690'
    weight = 10
    [backends.backend1.servers.server2]
    url = 'http://172.19.0.5:3690'
    weight = 10
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = 'http://172.19.0.4:3690'
    weight = 10
    [backends.backend2.servers.server2]
    url = 'http://172.19.0.3:3690'
    weight = 10
