
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

[log]

[api]
  insecure = true
  dashboard = true

[ping]

[providers]
  [providers.docker]
  [providers.file]
    directory = "/etc/traefik/config"
    watch = true