[global]
  logLevel = "INFO"
  checkNewVersion = false # 定期版本检查 默认 true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

  [entryPoints.see]
    address = ":8080"

[file]
filename="rules.toml"
watch = true

[log]
  [traefikLog]
    filePath = "log/traefik.log"
    format = "json"
  [accessLog]
    filePath = "log/access.log"
    format = "json"

[api]
  entryPoint = "see"
  dashboard = true
  defaultEntryPoints = ["http"]

[ping]

[providers.docker]
