version: "3"
services:
    node:
        image: node_img:latest
        restart: always
        volumes:
            - "/Users/zhaoguanxin/CODE/OTHER/traefik/node:/app"
        labels:
           - "traefik.http.routers.node.rule=Host(`node.docker.localhost`)"
           
networks:
    default:
        external:
            name: traefik_default
