version: "3"
services:
    node:
        image: tfnode:latest
        restart: always
        volumes:
            - "/Users/zhaoguanxin/CODE/OTHER/traefik/node:/app"
        labels:
            - "traefik.http.routers.node.rule=Host(`node.docker`)"
           
networks:
    default:
        external:
            name: traefik
